### ISSUE TITLE
New posts widget bug

### ISSUE THREAD

**Issue by dretax** [xfrocks/bdWidgetFramework#4]
New posts widget displays the original thread creator's name, and not the newest reply's post.

**Comment by daohoangson** [comment]
Are you still having this issue?

**Comment by dretax** [comment]
i will check it with the new version.

**Comment by dretax** [comment]
Yes, bug is still up.

**Comment by dretax** [comment]
@daohoangson

**Comment by daohoangson** [comment]
We have just released v2.6.4 with the fix for this. Can you try that version?

https://xfrocks.com/resources/bd-widget-framework.19/

**Comment by dretax** [comment]
Issue is verified as resolved. Thanks.
